version: '3'

services:
  gui:
    privileged: true
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/node/.p10k.zsh:delegated
      - ./.docker/zsh/history:/home/node/zsh:delegated
