version: '3'

services:
  vrsoft-talentpool-web:
    build: .
    container_name: VRSoft-TalentPool-WEB
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - '9876:9876'
      - '${PORT}:${PORT}'
    networks:
      - vrsoft-talentpool-net

networks:
  vrsoft-talentpool-net:
    driver: bridge
